### ISSUE TITLE
The loss becomes NAN in the fifth epochs training on 1 machine 

### ISSUE THREAD

**Issue by garyhujingyao** [diux-dev/imagenet18#19] opened 2018-10-12 01:21 UTC
Hi all,

I am trying to reproduce the result using one p3.16xlarge instance with the default setting.

After doing the AWS configure, I ran:

`python train.py --machines=1`

However, the loss becomes NAN in the fifth epoch:
 
![image](https://user-images.githubusercontent.com/27310173/46842206-59cc0280-cd9a-11e8-81a3-c4e44114a64d.png)

The full log file can be found [here](https://github.com/garyhujingyao/imagenet18/blob/master/verbose.log).

Does this mean that the default learning rate does not work? Or should I try the learning rate specified in the single machine log [here](https://github.com/diux-dev/imagenet18/tree/master/dawn/logs/single_machine). 

Thanks a lot.

**Comment by yaroslavvb** [comment] 2018-10-12 01:28
Can you try on a different AWS machine? The default settings should work, I tested single machine setting last week?

**Comment by garyhujingyao** [comment] 2018-10-12 01:33
Thank you for replying so quickly.

I will try it again, and see how it goes. Also, do we need to do the pre-warming for single machine mentioned in README?
![image](https://user-images.githubusercontent.com/27310173/46842734-4c644780-cd9d-11e8-98ac-eda797a83526.png)

**Comment by yaroslavvb** [comment] 2018-10-12 01:40
Without prewarming the time is about 10 min longer, it's not needed unless you are trying to set new speed record

**Comment by garyhujingyao** [comment] 2018-10-12 01:44
Okay, sounds good.

**Comment by garyhujingyao** [comment] 2018-10-12 02:31
Hi Yaroslav,

I tried to rerun the program on the same instance
`python train.py --machines=1`

However, this time it gives some error below
![image](https://user-images.githubusercontent.com/27310173/46844346-9e5c9b80-cda4-11e8-9950-600372f2ced8.png)

I am confused that should the `mkdir -p` command always return 0? Am I missing some reusing directories settings or should I delete the whole EFS and create a new one?

Thanks a lot!

**Comment by yaroslavvb** [comment] 2018-10-12 02:33
Probably your efs is not mounted, the script was designed to work on a
fresh new machine

**Comment by garyhujingyao** [comment] 2018-10-12 02:57
Okay, will try to mount efs to the instance or I can just start a new instance.

Thank you for being so responsive Yaroslav.

**Comment by mchitale** [comment] 2018-10-12 17:02
Hi,

We are still getting loss going to NaN. Please see screenshot attached below. 
We find that our test accuracy is decreasing from the beginning. And the train accuracy is initially increasing (though it fluctuates) as you can see in the plots. And then it just drops to NaNs. What do you think might be happening?
<img width="1438" alt="screen shot 2018-10-12 at 12 49 30 pm" src="https://user-images.githubusercontent.com/35814905/46882728-b7556300-ce1d-11e8-9c1a-14afd09d9ae1.png">

**Comment by yaroslavvb** [comment] 2018-10-12 17:05
Did you try on a different machine? Nans can be caused by machine problem.
Stanford team was able to run the code without getting Nan

**Comment by mchitale** [comment] 2018-10-12 17:48
Yeah, we ran it on a different machines both times.

**Comment by kbhardwa** [comment] 2018-10-12 19:37
Getting NaNs still. Tried three separate machines now. Also, we had to change "training/" from the path since that also gave us errors in train.py (we changed the path on this line: https://github.com/diux-dev/imagenet18/blob/master/train.py#L191). Apparently, the train_imagenet_nv.py file was present in both paths: training/ and the current directory. However, since train_imagenet_nv.py file imports various functions from training/ directory (e.g., https://github.com/diux-dev/imagenet18/blob/master/training/train_imagenet_nv.py#L29), train.py should call the train_imagenet_nv.py from current directory and not the one inside training directory. Are we doing something wrong?

**Comment by kbhardwa** [comment] 2018-10-12 22:23
Is disabling fp16 an option (since fp16 can sometimes lead to overflow NaNs problems)? Can you tell me how to disable fp16?

**Comment by yaroslavvb** [comment] 2018-10-13 18:32
fp16 is not supposed to lead to problems. I can try to reproduce your problem, can you give me instructions?

**Comment by yaroslavvb** [comment] 2018-10-13 18:33
You are not supposed to change anything in train.py, things should work out of the box, maybe that change is the cause of your problem

**Comment by kbhardwa** [comment] 2018-10-13 20:12
Hi Yaroslav, Thanks for getting back to us. 

I just tried again with the out-of-the-box code with a fresh copy of the git. Initially, all of the setup goes perfectly. However, like last time, when we use train.py out of the box, we get the following error inside the tmux:

`(pytorch_source) ubuntu@ip-172-31-77-152:~$ NCCL_DEBUG=VERSION python -m torch.distributed.launch --nproc_per_node=8 --nnodes=1 --node_rank=0 --master_addr=172.31.77.152 --master_port=6006 training/train_imagenet_nv.py ~/data/imagenet --fp16 --logdir /ncluster/runs/imagenet-1.07 --distributed --init-bn0 --no-bn-wd --phases "[{'ep': 0, 'sz': 128, 'bs': 512, 'trndir': '-sz/160'}, {'ep': (0, 7), 'lr': (1.0, 2.0)}, {'ep': (7, 13), 'lr': (2.0, 0.25)}, {'ep': 13, 'sz': 224, 'bs': 224, 'trndir': '-sz/352', 'min_scale': 0.087}, {'ep': (13, 22), 'lr': (0.4375, 0.043750000000000004)}, {'ep': (22, 25), 'lr': (0.043750000000000004, 0.004375)}, {'ep': 25, 'sz': 288, 'bs': 128, 'min_scale': 0.5, 'rect_val': True}, {'ep': (25, 28), 'lr': (0.0025, 0.00025)}]"; echo $? > /tmp/ncluster/0.imagenet-vv0oy/11.status
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "training/train_imagenet_nv.py", line 20, in <module>
  File "training/train_imagenet_nv.py", line 20, in <module>
  File "training/train_imagenet_nv.py", line 20, in <module>
            from training.fp16util import (model_grads_to_master_grads,from training.fp16util import (model_grads_to_master_grads,from training.fp16util import (model_grads_to_master_grads,


ModuleNotFoundError: ModuleNotFoundErrorNo module named 'training'ModuleNotFoundError:
: No module named 'training'No module named 'training'

Traceback (most recent call last):
  File "training/train_imagenet_nv.py", line 20, in <module>
    from training.fp16util import (model_grads_to_master_grads,
ModuleNotFoundError: No module named 'training'
Traceback (most recent call last):
  File "training/train_imagenet_nv.py", line 20, in <module>
    from training.fp16util import (model_grads_to_master_grads,
ModuleNotFoundError: No module named 'training'
Traceback (most recent call last):
  File "training/train_imagenet_nv.py", line 20, in <module>
    from training.fp16util import (model_grads_to_master_grads,
ModuleNotFoundError: No module named 'training'
Traceback (most recent call last):
  File "training/train_imagenet_nv.py", line 20, in <module>
    from training.fp16util import (model_grads_to_master_grads,
ModuleNotFoundError: No module named 'training'
Traceback (most recent call last):
  File "training/train_imagenet_nv.py", line 20, in <module>
    from training.fp16util import (model_grads_to_master_grads,
ModuleNotFoundError: No module named 'training'
(pytorch_source) ubuntu@ip-172-31-77-152:~$`

While trying to fix this, we found that train_imagenet_nv.py was present in both the current directory as well as the training/ directory. Hence, we figured that since the code is complaining "No module named 'training'", maybe we should have changed the path in the original command from `--master_port=6006 training/train_imagenet_nv.py ~/data/imagenet` to `--master_port=6006 **train_imagenet_nv.py** ~/data/imagenet`

The presence of train_imagenet.py in both locations can be easily verified by ls command as shown below:

`ubuntu@ip-172-31-77-152:~$ **ls -altrh *.py**
-rw-rw-r-- 1 ubuntu ubuntu  12K Aug  8 10:07 autoaugment.py
-rw-rw-r-- 1 ubuntu ubuntu  14K Aug  8 10:07 dataloader_performance.py
-rw-rw-r-- 1 ubuntu ubuntu 6.9K Aug 24 18:20 resnet.py
-rw-rw-r-- 1 ubuntu ubuntu 6.0K Aug 24 18:20 fp16util.py
-rw-rw-r-- 1 ubuntu ubuntu 7.8K Aug 24 18:20 dataloader.py
-rw-rw-r-- 1 ubuntu ubuntu 2.7K Aug 24 18:20 meter.py
-rw-rw-r-- 1 ubuntu ubuntu 2.9K Aug 24 18:20 logger.py
-rw-rw-r-- 1 ubuntu ubuntu  958 Aug 24 18:20 dist_utils.py
-rw-rw-r-- 1 ubuntu ubuntu  21K Aug 24 18:20 **train_imagenet_nv.py**
-rw-rw-r-- 1 ubuntu ubuntu 1.1K Aug 24 18:20 experimental_utils.py
ubuntu@ip-172-31-77-152:~$ **ls -altrh training/**
total 112K
-rw-rw-r--  1 ubuntu ubuntu  30K Aug 25 20:00 train_imagenet_nv.bak.py
drwxrwxr-x  2 ubuntu ubuntu 4.0K Aug 25 20:00 __pycache__
-rw-rw-r--  1 ubuntu ubuntu  21K Oct 13 19:34 **train_imagenet_nv.py**
-rw-rw-r--  1 ubuntu ubuntu    0 Oct 13 19:34 __init__.py
drwxrwxr-x  3 ubuntu ubuntu 4.0K Oct 13 19:34 .
-rw-rw-r--  1 ubuntu ubuntu 8.1K Oct 13 19:34 dataloader.py
-rw-rw-r--  1 ubuntu ubuntu 1.1K Oct 13 19:34 experimental_utils.py
-rw-rw-r--  1 ubuntu ubuntu 1017 Oct 13 19:34 dist_utils.py
-rw-rw-r--  1 ubuntu ubuntu 2.8K Oct 13 19:34 meter.py
-rw-rw-r--  1 ubuntu ubuntu 3.9K Oct 13 19:34 logger.py
-rw-rw-r--  1 ubuntu ubuntu 7.0K Oct 13 19:34 resnet.py
-rw-rw-r--  1 ubuntu ubuntu 6.1K Oct 13 19:34 fp16util.py
drwxr-xr-x 25 ubuntu ubuntu 4.0K Oct 13 19:55 ..`

Can you please advise us what to do? Thanks a lot!

**Comment by yaroslavvb** [comment] 2018-10-13 20:14
Uh oh, I wonder if the last pull request broke things...will try later today

**Comment by kbhardwa** [comment] 2018-10-13 20:32
Thanks so much!

**Comment by yaroslavvb** [comment] 2018-10-17 01:08
The problem with training.py was due to last PR which I merged without testing, reverted it, and started run, will report if I get nan after 5 epochs in us-west-2

**Comment by yaroslavvb** [comment] 2018-10-17 02:11
Seems to work with no nan's for me, can you try with fresh sync?
```
Epoch: [23][280/715]    Time 0.290 (0.318)      Loss 1.1693 (1.1644)    Acc@1 72.656 (72.098)   Acc@5 88.895 (89.210)   Data 0.003 (0.038)      BW 0.000 0.000
Epoch: [23][285/715]    Time 0.283 (0.317)      Loss 1.1770 (1.1636)    Acc@1 71.987 (72.104)   Acc@5 88.839 (89.222)   Data 0.004 (0.038)      BW 0.000 0.000
Epoch: [23][290/715]    Time 0.305 (0.317)      Loss 1.1653 (1.1635)    Acc@1 70.815 (72.096)   Acc@5 88.895 (89.223)   Data 0.003 (0.038)      BW 0.000 0.000
Epoch: [23][295/715]    Time 0.289 (0.317)      Loss 1.1837 (1.1641)    Acc@1 71.931 (72.076)   Acc@5 88.449 (89.218)   Data 0.016 (0.038)      BW 0.000 0.000
Epoch: [23][300/715]    Time 0.282 (0.317)      Loss 1.1207 (1.1636)    Acc@1 72.600 (72.088)   Acc@5 89.844 (89.221)   Data 0.003 (0.038)      BW 0.000 0.000
```

**Comment by kbhardwa** [comment] 2018-10-17 02:17
Okay thanks Yaroslav. We'll try it out by tomorrow or so and keep you posted. Also, do we need to reinstall ncluster, etc. for this (i.e., was there any change in any of the dependencies like ncluster) or can we just clone the latest imagenet18 git and that should suffice?

**Comment by kbhardwa** [comment] 2018-10-17 17:38
Thanks a lot Yaroslav. It works now as expected. I got 76% top1 and 93% top5 in 1.5 hours or so on 1 machine. This is truly excellent :)

**Closed as completed** 2018-10-22 16:25 UTC
